### ISSUE TITLE
This project is not working anymore

### ISSUE THREAD

**Issue by christopheblin** [davidillsley/keycloak-swarm-heroku#1]
When I try to deploy the project to heroku, I encounter the following error.
[herokulogs.txt](https://github.com/davidillsley/keycloak-swarm-heroku/files/586351/herokulogs.txt)

Could you give some inputs of what is going wrong.

Thanks in advance,

**Comment by christopheblin** [comment]
The fork https://github.com/sammyrulez/keycloak-swarm-heroku is nearly ok but the page fails to load...

I think that the problem is that there is no admin configured on first start but no info on that either

**Comment by klausboeing** [comment]
Updated to last swarm and keycloak version and admin/admin credentials in first access.

https://github.com/klausboeing/keycloak-swarm-heroku
